apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-qb0z
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ghoa-tenant/rhtap-demo-app/hacbs-test-project-qb0z@sha256:13744a1c88d315821c47132e157409780b8532ac1c710e41fbcd7f4ac2414f78
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
