apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qb0z
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qb0z
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qb0z
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qb0z
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qb0z
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ghoa-tenant/rhtap-demo-app/hacbs-test-project-qb0z@sha256:af2c4187b105661d3d9e5ba7700c4229359bd0579ee80f2b44a18190b7bd9190
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
